FROM apache/superset:latest

USER root

RUN pip install --upgrade pip
RUN apt-get update && apt-get install -y build-essential pkg-config default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install mysqlclient psycopg2-binary

ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_EMAIL $ADMIN_EMAIL
ENV ADMIN_PASSWORD $ADMIN_PASSWORD

COPY ./superset-init.sh /superset-init.sh
RUN chmod +x /superset-init.sh

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

USER superset
ENTRYPOINT [ "/superset-init.sh" ]